language: node_js
node_js:
 - "5.4.1"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - python -m SimpleHTTPServer &
  - sleep 2

script: npm install && npm run build && npm run testfunc

addons:
  sauce_connect: true
