language: node_js
node_js:
 - "5.4.1"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - python -m SimpleHTTPServer &
  - sleep 2

script: npm install && npm run build && npm run testfunc

addons:
  sauce_connect: true
